zero_click_sso:
  zero_click_sso_enabled:
    default: false
    client: true
  zero_click_sso_enabled_for_noisy_providers:
    default: false
    client: true
  zero_click_sso_consider_custom_providers_silently:
    default: false
    client: true
